n = input('Digite algo: ')
print('É uma letra? ')
print(n.isalpha())
print('As letras estão maiúsculas? ')
print(n.isupper())
print('É um número? ')
print(n.isnumeric())
print('É AlfaNumérico?')
print(n.isalnum())
print('Está em ASCII?')
print(n.isascii())
print('Só tem espaços?')
print(n.isspace())
print('Está tudo em minúsculas?')
print(n.islower())
print('Está capitalizada?', n.istitle())
